### ISSUE TITLE
Would this work for multiple node servers using same redis instance?

### ISSUE THREAD

**Issue by brettjonesdev** [errorception/redis-lock#15]
I'm working on a project which involves multiple node servers running and querying/updating the same redis instance, and am investigating a locking mechanism to prevent simultaneous updates from overwriting each other.  Does your implementation only enforce locking for a single node instance, or would it work across multiple node vms?

**Comment by rakeshpai** [comment]
Locks are held across node instances, as long as they use the same redis server. If one process acquires a lock, other processes can't acquire the same lock, until the first process releases it, or times out.

**Comment by brettjonesdev** [comment]
Thanks for the response!
