### ISSUE TITLE
Lock isn't working when multiple servers are needing locks

### ISSUE THREAD

**Issue by BrandonCopley** [errorception/redis-lock#23]
If I have this running on 4 different machines all connected to the same database we are seeing that the lock's aren't being made. Does this lock work across multiple servers?

**Comment by rakeshpai** [comment]
Yes, locks work across multiple machines, as long as they all talk to the same redis instance. The tests should demonstrate this, so I suggest giving it a look. Otherwise, I'd need more details to be able to debug your scenario.

**Comment by BrandonCopley** [comment]
Okay, I'm working on debugging now.

**Comment by BrandonCopley** [comment]
We are debugging, this does appear to work, We had a typo in our code and "unlock" wasn't existing in a callback. Thanks!
