### ISSUE TITLE
Is it possible to have `acquire` wait forever

### ISSUE THREAD

**Issue by paulgrove** [errorception/redis-lock#27]
I would like a Mutex that may possibly wait forever, is this possible?

**Comment by rakeshpai** [comment]
TBH, I'm not sure. You could try setting the timeout to `Infinity`. The [timeout value is just passed along](https://github.com/errorception/redis-lock/blob/master/index.js#L15) to `redis` as is, so it depends on what the `redis` lib supports, and what it sends to the redis server itself. Sorry I don't have a better answer. You'll just have to try it. It would be great if you can report back with your findings.
