### ISSUE TITLE
Delete lock objects that have not been used in a long time

### ISSUE THREAD

**Issue by objectiveSee** [errorception/redis-lock#9]
Just an idea....

**Comment by daniloaburto** [comment]
+1

**Comment by SimoneTaliercio** [comment]
+1

**Comment by rakeshpai** [comment]
Closing this as it's an old issue. If this is still relevant, feel free to reopen. Also, it would be great if you could point out which lock objects you're referring to. AFAICT, things should be automatically GC'd, and there shouldn't be any references held. Am I missing something?
